cask_args appdir: '/Applications'
tap 'caskroom/cask'
brew 'ctags'
brew 'ack'
brew 'python'
brew 'emacs'
brew 'tmux'
brew 'byobu'
#brew 'perl'
#brew 'cpanminus'
#brew 'zsh'
#brew 'mas'
brew 'erlang'
brew 'ghc'
brew 'cabal-install'
# cabal update
brew 'coreutils'